name: FluidAttacks Pipeline
on: [push, pull_request]

jobs:
  # 1. Escaneo de dependencias (SCA) modo tolerante
   SCA:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
         - uses: docker://docker.io/fluidattacks/sca:latest
           name: SCA_Fluidattacks
           with:
             args: sca scan .

  # 2. Escaneo SAST modo tolerante; sólo se ejecuta si el anterior terminó
   SAST:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
         - uses: docker://docker.io/fluidattacks/sast:latest
           name: SAST_Fluidattacks
           with:
             args: sast scan .
  forces:
    runs-on: ubuntu-latest
    container:
      image: fluidattacks/forces:latest
    steps:
      - name: Run Agent check
        run: forces --token $TOKEN_AGENT
